export const FETCHING_PRODUCT_TYPE = 'FETCHING_PRODUCT_TYPE';
export const FETCHING_TOP_PRODUCT = 'FETCHING_TOP_PRODUCT';
export const FETCHING_TOP_PRODUCT_SUCCESS = 'FETCHING_TOP_PRODUCT_SUCCESS';
export const FETCHING_PRODUCT_TYPE_SUCCESS = 'FETCHING_PRODUCT_TYPE_SUCCESS';
export const FETCHING_DATA_FAILURE = 'FETCHING_DATA_FAILURE';
