export const FETCHING_PRODUCT_TYPE = 'FETCHING_PRODUCT_TYPE';
export const FETCHING_PRODUCT_TYPE_SUCCESS = 'FETCHING_PRODUCT_TYPE_SUCCESS';
export const FETCHING_DATA_FAILURE = 'FETCHING_DATA_FAILURE';
